In [68]:
import numpy as np

In [19]:
# import gmplot package
import gmplot

latitude_list = [ 40.76372909545898, 40.77077865600585, 40.722164154052734, 40.75267028808594,40.75885391235352, 40.76372909545898 ]
longitude_list = [-73.97139739990234, -73.95086669921875,-73.99718475341797, -73.98885345458984, -73.97631072998048, -73.97139739990234 ] 

gmap3 = gmplot.GoogleMapPlotter(40.73183233384461, -73.98824417559939, 13, apikey = "AIzaSyBu4QYj7iUTocxC38xa-H7bF9pqcXEDhT8")
# scatter method of map object
# scatter points on the google map
gmap3.scatter( latitude_list, longitude_list, '#FF0000',size = 40, marker = False )
gmap3.scatter( [latitude_list[0]], [longitude_list[0]], '#ADFF2F',
                              size = 40, marker = True )
#
# Plot method Draw a line in
# between given coordinates
gmap3.plot(latitude_list, longitude_list, 'cornflowerblue', edge_width = 2.5)
gmap3.draw( "map.html" )

In [3]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
plt.figure(figsize=(8, 8))
m = Basemap(projection='ortho', resolution=None, lat_0=50, lon_0=-100)
m.bluemarble(scale=0.5);

In [8]:
!pip install folium

'DOSKEY' is not recognized as an internal or external command,
operable program or batch file.


In [115]:
#converts html into png

from GrabzIt import GrabzItImageOptions
from GrabzIt import GrabzItClient
import folium

def html_str(file):
    res = ""
    with open(file) as infile:
        for l in infile:
            res += f"{l}"
    return res

def png_map(latlon, i, co):
    NYC_map = folium.Map(location = [40.75483470057502, -73.94284652957808], tiles="OpenStreetMap", zoom_start = 13)
    from GrabzIt import GrabzItImageOptions
    
    folium.Marker( location=[latlon[0][0], latlon[0][1]], fill_color='#00FF00', 
                  icon=folium.Icon(color="blue"), radius=1 ).add_to( NYC_map )
    for coord in latlon[1:]:
        folium.Circle(radius=80, location=[coord[0], coord[1]], color="#3186cc", fill=False).add_to(NYC_map)
    #latlon.append(latlon[0])
    folium.PolyLine(latlon, color=co, weight=2.5, opacity=1).add_to(NYC_map)
    
    NYC_map.save(f"map{i}.html")
    file = html_str(f"map{i}.html")
    grabzIt = GrabzItClient.GrabzItClient("OWE2Y2MyYWI4MzY2NGFkMTk5ZjBiZGU5ODRiNTI2NWE=", "Pz9xPz8/PwY/Pz9oOw0iTD8/eFI2Pz8/cD8/P3g/NEM=")
    options = GrabzItImageOptions.GrabzItImageOptions()
    options.browserWidth = 1280
    options.browserHeight = 582
    options.width = 1280
    options.height = 1000
    options.format = "png"
    grabzIt.HTMLToImage(file, options)
    grabzIt.SaveTo(f"./images/map{i}.png")

def convertMap(points):
    n = len(points)
    for i in range(n - 1):
        png_map(points[i], i, "red")
    png_map(points[n - 1], n - 1, "green")

d = []
ans = []
with open('dictionary.txt', 'r') as dictionary:
    rest = dictionary.readlines()
    for i in range(len(rest)):
        rest[i] = rest[i].split(' ')
        d.append((float(rest[i][1]), float(rest[i][0])))
        #print((float(rest[i][0]), float(rest[i][1])))

#lst = [d[i] for i in range(40)]
#ans.append(lst)
#print(ans)
#convertMap(ans)
        
road = np.load('gif.npy')

print(road)
for path in road:
    tmp = []
    for i,element in enumerate(path):
        tmp.append(d[element])
    if len(ans) > 0 and tmp == ans[-1]:
        continue
    ans.append(tmp)
#print(ans)
convertMap(ans)
    

[[ 0 33 29 ... 18 32  0]
 [ 0 33 29 ... 18 32  0]
 [ 0 44  6 ... 18 32  0]
 ...
 [ 0 30 28 ... 20 43  0]
 [ 0 14 46 ... 20 43  0]
 [ 0 43 30 ... 20 28  0]]
